gemfile

jarfile

group_id "com.mvnrails"
artifact_id "mvn-rails-web"
version "1.0-SNAPSHOT"
packaging "jar"

name "mvn-rails-web"
description "A demo rails app using maven dependencies"

parent "com.mvnrails:mvn-rails", "1.0-SNAPSHOT"

properties( 'tesla.dump.pom' => 'pom.xml' )

phase :package do
  plugin 'de.saumya.mojo:gem-maven-plugin' do
    execute_goal( :exec,
                  :id => 'pack-war with warbler',
                  :filename => 'warble' )
  end
end